import sys
import os
import re

# =================CONFIGURATION=================
INPUT_FILE = "Hearty.ino"
OUTPUT_FILE = "Hearty_DEBUG_GEN.h"
# ===============================================

def generate_debug_version(input_path, output_path):
    print(f"Processing {input_path}...")

    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"ERROR: Could not find input file: {input_path}")
        sys.exit(1)

    # Define Regex Patterns for custom debug comments
    # \s* matches optional whitespace
    # (.*?) captures arguments non-greedily
    replacements = [
        # Matches: /* s_begin(115200) */
        (r'/\*\s*s_begin\((.*?)\)\s*\*/', r'Serial.begin(\1);'),

        # Matches: /* s_print("Value: ") */
        (r'/\*\s*s_print\((.*?)\)\s*\*/', r'Serial.print(\1);'),

        # Matches: /* s_println(x) */
        (r'/\*\s*s_println\((.*?)\)\s*\*/', r'Serial.println(\1);\n  Serial.flush();'),

        # Matches: /* s_printf("Val: %d\n", x) */
        # DOTALL flag needed if printf arguments span multiple lines
        (r'/\*\s*s_printf\((.*?)\)\s*\*/', r'Serial.printf(\1);'),

        # Matches: /* s_flush() */
        (r'/\*\s*s_flush\(\)\s*\*/', r'Serial.flush();'),
        
        # Matches generic debug blocks: /* DEBUG_BLOCK: { some code } */
        # Useful for things like the large serial command handler block
        (r'/\*\s*DEBUG_BLOCK:\s*(.*?)\s*\*/', r'\1'),
    ]

    processed_content = content
    countTotal = 0

    for pattern, replacement in replacements:
        # Use DOTALL for flexibility in multi-line comments
        regex = re.compile(pattern, re.DOTALL)
        processed_content, count = regex.subn(replacement, processed_content)
        countTotal += count

    header = "// ==================================================\n"
    header += "// WARNING: GENERATED FILE. DO NOT EDIT MANUALLY.\n"
    header += f"// Source file: {INPUT_FILE}\n"
    header += "// generated by python script.\n"
    header += "// ==================================================\n\n"

    final_output = header + processed_content

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_output)

    print(f"Success! Un-commented {countTotal} debug statements.")
    print(f"Generated file saved as: {output_path}")
    print("Open the generated file in Arduino IDE to upload debug version.")

if __name__ == "__main__":
    # Determine paths based on where script runs
    script_dir = os.path.dirname(os.path.abspath(__file__))
    in_path = os.path.join(script_dir, INPUT_FILE)
    out_path = os.path.join(script_dir, OUTPUT_FILE)
    
    generate_debug_version(in_path, out_path)